#!/bin/sh

set -e

VENV="${VENV:-/var/tmp/venv}"
log(){ echo "$*" >&2; }

log "Running as $(id -u):$(id -g)"

if [ -n "$UMASK" ]; then
  log "Setting umask to $UMASK"
  umask "$UMASK"
fi

log "Initializing venv in $VENV"
python3 -m venv --system-site-packages "$VENV"
. "$VENV/bin/activate"

log "Starting homeassistant"
set -- ${@:-python3 -m homeassistant --config /config}
# replace the current pid 1 with the original command
exec "$@"
